"""Add User model

Revision ID: aeaf4f8c0ac1
Revises: 83824030ebbf
Create Date: 2024-01-05 09:54:00.781062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaf4f8c0ac1'
down_revision = '83824030ebbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
